<a href="https://colab.research.google.com/github/Debabrat1/Indian-Flight-Networks/blob/main/M_Tech_adj_matrix_Debabrat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Import numpy and pandas packages

In [ ]:
import pandas as pd
import numpy as np

file =('/content/drive/MyDrive/M.Tech_main Project work/flight.xlsx')
## Removing Unnecessary Rows and Colums from the Excel Sheet
flightData = pd.read_excel(file, usecols="C,D,E", skiprows=0)
print(flightData)

    Airport Names Airport(Arrival)  Frequency per week
0        Agartala        Bangalore                   7
1             NaN            Delhi                   7
2             NaN         Guwahati                  25
3             NaN           Imphal                   7
4             NaN          Kolkata                  77
..            ...              ...                 ...
875        Thoise            Delhi                   2
876     Passighat         Guwahati                   4
877       Pakyong          Kolkata                   7
878   Pondicherry        Bangalore                   5
879           NaN        Hyderabad                   7

[880 rows x 3 columns]


In [ ]:
## Using PAD Fill to Fill Up the Empty Columns in City Name
flightData.fillna(method='pad', inplace=True)
print(flightData.to_string())


     Airport Names Airport(Arrival)  Frequency per week
0         Agartala        Bangalore                   7
1         Agartala            Delhi                   7
2         Agartala         Guwahati                  25
3         Agartala           Imphal                   7
4         Agartala          Kolkata                  77
5           Agatti           Cochin                  14
6        Ahmedabad       Aurangabad                  13
7        Ahmedabad         Bagdogra                  13
8        Ahmedabad        Bangalore                  76
9        Ahmedabad          Belgaum                   7
10       Ahmedabad        Bhavnagar                   6
11       Ahmedabad           Bhopal                  14
12       Ahmedabad     Bhubaneshwar                   7
13       Ahmedabad       Chandigarh                  27
14       Ahmedabad          Chennai                  55
15       Ahmedabad           Cochin                  14
16       Ahmedabad         Dehradun             

In [ ]:
## Converting the city names to index based on dictionary

cityDict = { "Delhi" : 0, "Mumbai" : 1, "Kolkata" : 2, "Chennai" : 3, "Agartala" : 4, "Agatti" : 5, "Ahmedabad" : 6, "Bhavnagar" : 7, "Porbandar" : 8, "Jammnagar" : 9, "Rajkot" : 10, "Bhuj" : 11, "Kandla" : 12, "Surat" : 13, "Vadodara" : 14, "Aizawal" : 15, "Agra" : 16, "Allahabad" : 17, "Gorakhpur" : 18, "Hindon" : 19, "Kanpur" : 20, "Lucknow" : 21, "Varanashi" : 22, "Adampur" : 23, "Amritsar" : 24, "Bathinda" : 25, "Chandigarh" : 26, "Bagdogra" : 27, "Durgapur" : 28, "Bangalore" : 29, "Belgaum" : 30, "Hubli" : 31, "Mangalore" : 32, "Vidyanagar" : 33, "Mysore" : 34, "Bhopal" : 35, "Gwalior" : 36, "Indore" : 37, "Khajuraho" : 38, "Jabalpur" : 39, "Bhubaneshwar" : 40, "Jharsuguda" : 41, "Calicut" : 42, "Cochin" : 43, "Kannur" : 44, "Trivandrum" : 45, "Coimbatore" : 46, "Madurai" : 47, "Trichy" : 48, "Tuticorin" : 49, "Salem" : 50, "Dehradun" : 51, "Pantnagar" : 52, "Pithoragarh" : 53, "Dibrugarh" : 54, "Guwahati" : 55, "Jorhat" : 56, "Silchar" : 57, "Tezpur" : 58, "Lilabari" : 59, "Dimapur" : 60, "Gaya" : 61, "Patna" : 62, "Goa" : 63, "Hyderabad" : 64, "Imphal" : 65, "Bikaner" : 66, "Jaipur" : 67, "Jaisalmer" : 68, "Jodhpur" : 69, "Kishangarh" : 70, "Udaipur" : 71, "Jammu" : 72, "Srinagar" : 73, "Aurangabad" : 74, "Kolhapur" : 75, "Nagpur" : 76, "Pune" : 77, "Shirdi" : 78, "Nashik" : 79, "Nanded" : 80, "Jalgaon" : 81, "Port Blair" : 82, "Jagdalpur" : 83, "Raipur" : 84, "Cuddapah" : 85, "Rajahmundry" : 86, "Tirupathi" : 87, "Vijaywada" : 88, "Visakhapatnam" : 89, "Ranchi" : 90, "Shillong" : 91, "Dharamshala" : 92, "Kullu" : 93, "Shimla" : 94, "Diu" : 95, "Leh" : 96, "Thoise" : 97, "Passighat" : 98, "Pakyong" : 99, "Pondicherry" : 100, "Belagavi" : 101, "Kadapa" : 102, "Andal" : 103, "Ludhiana" : 104, "Pathankot" : 105, "Patnagar" : 106, "Kangra" : 107, "Meerut" : 108, "Bidar" :109, }
inv_cityDict = {v: k for k, v in cityDict.items()}
print(inv_cityDict)
print(len(cityDict))

{0: 'Delhi', 1: 'Mumbai', 2: 'Kolkata', 3: 'Chennai', 4: 'Agartala', 5: 'Agatti', 6: 'Ahmedabad', 7: 'Bhavnagar', 8: 'Porbandar', 9: 'Jammnagar', 10: 'Rajkot', 11: 'Bhuj', 12: 'Kandla', 13: 'Surat', 14: 'Vadodara', 15: 'Aizawal', 16: 'Agra', 17: 'Allahabad', 18: 'Gorakhpur', 19: 'Hindon', 20: 'Kanpur', 21: 'Lucknow', 22: 'Varanashi', 23: 'Adampur', 24: 'Amritsar', 25: 'Bathinda', 26: 'Chandigarh', 27: 'Bagdogra', 28: 'Durgapur', 29: 'Bangalore', 30: 'Belgaum', 31: 'Hubli', 32: 'Mangalore', 33: 'Vidyanagar', 34: 'Mysore', 35: 'Bhopal', 36: 'Gwalior', 37: 'Indore', 38: 'Khajuraho', 39: 'Jabalpur', 40: 'Bhubaneshwar', 41: 'Jharsuguda', 42: 'Calicut', 43: 'Cochin', 44: 'Kannur', 45: 'Trivandrum', 46: 'Coimbatore', 47: 'Madurai', 48: 'Trichy', 49: 'Tuticorin', 50: 'Salem', 51: 'Dehradun', 52: 'Pantnagar', 53: 'Pithoragarh', 54: 'Dibrugarh', 55: 'Guwahati', 56: 'Jorhat', 57: 'Silchar', 58: 'Tezpur', 59: 'Lilabari', 60: 'Dimapur', 61: 'Gaya', 62: 'Patna', 63: 'Goa', 64: 'Hyderabad', 65: 'Imph

In [ ]:
## Replacing the Names with Indices using Dictionary
flightData.replace(cityDict, inplace=True)
print(flightData.to_string())


     Airport Names  Airport(Arrival)  Frequency per week
0                4                29                   7
1                4                 0                   7
2                4                55                  25
3                4                65                   7
4                4                 2                  77
5                5                43                  14
6                6                74                  13
7                6                27                  13
8                6                29                  76
9                6                30                   7
10               6                 7                   6
11               6                35                  14
12               6                40                   7
13               6                26                  27
14               6                 3                  55
15               6                43                  14
16               6             

In [ ]:
## Creating the Matrix with Zero Values
## len function is used to calculate the length of the dictionary
cityArray = np.zeros((len(cityDict), len(cityDict)))
print(cityArray)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
## Iterating the DataFrame to insert value at the adjacency matrix
for i in range(len(flightData)) :

    print(flightData.iloc[i, 0], flightData.iloc[i, 1], flightData.iloc[i, 2])
    cityArray[int(flightData.iloc[i, 0]), int(flightData.iloc[i, 1])] = int(flightData.iloc[i, 2])

4 29 7
4 0 7
4 55 25
4 65 7
4 2 77
5 43 14
6 74 13
6 27 13
6 29 76
6 30 7
6 7 6
6 35 14
6 40 7
6 26 27
6 3 55
6 43 14
6 51 13
6 0 172
6 95 6
6 63 27
6 55 6
6 31 7
6 64 59
6 37 40
6 39 6
6 67 39
6 68 12
6 81 7
6 69 13
6 12 13
6 20 6
6 70 6
6 2 29
6 21 29
6 108 6
6 1 88
6 76 13
6 79 13
6 62 6
6 8 7
6 77 41
6 73 7
6 71 6
6 22 20
7 6 6
7 13 6
8 6 7
8 1 7
9 1 7
10 0 14
10 1 21
11 1 7
12 6 12
12 1 7
13 29 14
13 7 6
13 3 14
13 0 42
13 63 21
13 64 14
13 67 10
13 68 7
13 2 28
13 1 7
13 76 7
13 71 7
14 29 15
14 0 49
14 64 7
14 1 22
14 76 14
15 55 14
15 65 4
15 2 21
16 67 4
17 35 7
17 29 7
17 0 28
17 2 21
17 1 7
17 84 21
18 29 7
18 0 14
18 64 7
18 2 7
18 1 7
19 31 3
19 53 7
20 6 6
20 0 7
20 1 14
21 6 36
21 29 41
21 3 7
21 51 6
21 0 147
21 63 8
21 64 20
21 2 28
21 1 63
21 62 14
21 77 7
21 73 7
22 6 19
22 6 13
22 29 27
22 40 7
22 3 18
22 51 3
22 0 127
22 61 15
22 64 36
22 67 11
22 38 12
22 2 33
22 1 56
23 0 7
24 29 7
24 51 2
24 0 87
24 64 7
24 67 7
24 2 7
24 1 16
24 62 11
24 73 14
25 0 3
26 6 23
26

In [ ]:
## tolist function converts the values to Float values. Hence specifying the type explicitly 
#print(np.matrix(cityArray.astype(np.int32).tolist()))
output_df = pd.DataFrame(cityArray)
output_df.rename(index=dict(inv_cityDict), columns=dict(inv_cityDict), inplace=True)

In [ ]:
output_df

Delhi  Mumbai  Kolkata  Chennai  ...  Patnagar  Kangra  Meerut  Bidar
Delhi        0.0   328.0    142.0     77.0  ...       4.0     6.0     0.0    0.0
Mumbai     457.0     0.0    178.0    154.0  ...       0.0     0.0     0.0    0.0
Kolkata    278.0   169.0      0.0    120.0  ...       0.0     0.0     0.0    0.0
Chennai    170.0   157.0    102.0      0.0  ...       0.0     0.0     0.0    0.0
Agartala     7.0     0.0     77.0      0.0  ...       0.0     0.0     0.0    0.0
...          ...     ...      ...      ...  ...       ...     ...     ...    ...
Pathankot    0.0     0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0
Patnagar     0.0     0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0
Kangra       0.0     0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0
Meerut       0.0     0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0
Bidar        0.0     0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0

[110 rows x 110 columns]

In [ ]:
filepath = 'output.xlsx'
output_df.to_excel(filepath, index=True)