<a href="https://colab.research.google.com/github/Debabrat1/Indian-Flight-Networks/blob/main/Normalization_flight_networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Import numpy and pandas packages

In [ ]:
import pandas as pd
import numpy as np

file =('/content/drive/MyDrive/Sudip_Sir/flightt.xlsx')
## Removing Unnecessary Rows and Colums from the Excel Sheet
flightData = pd.read_excel(file, usecols="C,D,E", skiprows=0)
print(flightData)

    Airport Names Airport(Arrival)  Frequency per week
0        Agartala        Bangalore                   7
1             NaN            Delhi                   7
2             NaN         Guwahati                  25
3             NaN           Imphal                   7
4             NaN          Kolkata                  77
..            ...              ...                 ...
874        Thoise            Delhi                   2
875     Passighat         Guwahati                   4
876       Pakyong          Kolkata                   7
877   Pondicherry        Bangalore                   5
878           NaN        Hyderabad                   7

[879 rows x 3 columns]


In [ ]:
## Using PAD Fill to Fill Up the Empty Columns in City Name
flightData.fillna(method='pad', inplace=True)
print(flightData.to_string())

     Airport Names Airport(Arrival)  Frequency per week
0         Agartala        Bangalore                   7
1         Agartala            Delhi                   7
2         Agartala         Guwahati                  25
3         Agartala           Imphal                   7
4         Agartala          Kolkata                  77
5           Agatti           Cochin                  14
6        Ahmedabad       Aurangabad                  13
7        Ahmedabad         Bagdogra                  13
8        Ahmedabad        Bangalore                  76
9        Ahmedabad          Belgaum                   7
10       Ahmedabad        Bhavnagar                   6
11       Ahmedabad           Bhopal                  14
12       Ahmedabad     Bhubaneshwar                   7
13       Ahmedabad       Chandigarh                  27
14       Ahmedabad          Chennai                  55
15       Ahmedabad           Cochin                  14
16       Ahmedabad         Dehradun             

In [ ]:
## Converting the city names to index based on dictionary

cityDict = { "Delhi" : 0, "Mumbai" : 1, "Kolkata" : 2, "Chennai" : 3, "Agartala" : 4, "Agatti" : 5, "Ahmedabad" : 6, "Bhavnagar" : 7, "Porbandar" : 8, "Jammnagar" : 9, "Rajkot" : 10, "Bhuj" : 11, "Kandla" : 12, "Surat" : 13, "Vadodara" : 14, "Aizawal" : 15, "Agra" : 16, "Allahabad" : 17, "Gorakhpur" : 18, "Hindon" : 19, "Kanpur" : 20, "Lucknow" : 21, "Varanashi" : 22, "Adampur" : 23, "Amritsar" : 24, "Bathinda" : 25, "Chandigarh" : 26, "Bagdogra" : 27, "Durgapur" : 28, "Bangalore" : 29, "Belgaum" : 30, "Hubli" : 31, "Mangalore" : 32, "Vidyanagar" : 33, "Mysore" : 34, "Bhopal" : 35, "Gwalior" : 36, "Indore" : 37, "Khajuraho" : 38, "Jabalpur" : 39, "Bhubaneshwar" : 40, "Jharsuguda" : 41, "Calicut" : 42, "Cochin" : 43, "Kannur" : 44, "Trivandrum" : 45, "Coimbatore" : 46, "Madurai" : 47, "Trichy" : 48, "Tuticorin" : 49, "Salem" : 50, "Dehradun" : 51, "Pantnagar" : 52, "Pithoragarh" : 53, "Dibrugarh" : 54, "Guwahati" : 55, "Jorhat" : 56, "Silchar" : 57, "Tezpur" : 58, "Lilabari" : 59, "Dimapur" : 60, "Gaya" : 61, "Patna" : 62, "Goa" : 63, "Hyderabad" : 64, "Imphal" : 65, "Bikaner" : 66, "Jaipur" : 67, "Jaisalmer" : 68, "Jodhpur" : 69, "Kishangarh" : 70, "Udaipur" : 71, "Jammu" : 72, "Srinagar" : 73, "Aurangabad" : 74, "Kolhapur" : 75, "Nagpur" : 76, "Pune" : 77, "Shirdi" : 78, "Nashik" : 79, "Nanded" : 80, "Jalgaon" : 81, "Port Blair" : 82, "Jagdalpur" : 83, "Raipur" : 84, "Cuddapah" : 85, "Rajahmundry" : 86, "Tirupathi" : 87, "Vijaywada" : 88, "Visakhapatnam" : 89, "Ranchi" : 90, "Shillong" : 91, "Dharamshala" : 92, "Kullu" : 93, "Shimla" : 94, "Diu" : 95, "Leh" : 96, "Thoise" : 97, "Passighat" : 98, "Pakyong" : 99, "Pondicherry" : 100, "Belagavi" : 101, "Kadapa" : 102, "Andal" : 103, "Ludhiana" : 104, "Pathankot" : 105, "Patnagar" : 106, "Kangra" : 107, "Meerut" : 108, "Bidar" :109, }
inv_cityDict = {v: k for k, v in cityDict.items()}
print(inv_cityDict)
print(len(cityDict))

{0: 'Delhi', 1: 'Mumbai', 2: 'Kolkata', 3: 'Chennai', 4: 'Agartala', 5: 'Agatti', 6: 'Ahmedabad', 7: 'Bhavnagar', 8: 'Porbandar', 9: 'Jammnagar', 10: 'Rajkot', 11: 'Bhuj', 12: 'Kandla', 13: 'Surat', 14: 'Vadodara', 15: 'Aizawal', 16: 'Agra', 17: 'Allahabad', 18: 'Gorakhpur', 19: 'Hindon', 20: 'Kanpur', 21: 'Lucknow', 22: 'Varanashi', 23: 'Adampur', 24: 'Amritsar', 25: 'Bathinda', 26: 'Chandigarh', 27: 'Bagdogra', 28: 'Durgapur', 29: 'Bangalore', 30: 'Belgaum', 31: 'Hubli', 32: 'Mangalore', 33: 'Vidyanagar', 34: 'Mysore', 35: 'Bhopal', 36: 'Gwalior', 37: 'Indore', 38: 'Khajuraho', 39: 'Jabalpur', 40: 'Bhubaneshwar', 41: 'Jharsuguda', 42: 'Calicut', 43: 'Cochin', 44: 'Kannur', 45: 'Trivandrum', 46: 'Coimbatore', 47: 'Madurai', 48: 'Trichy', 49: 'Tuticorin', 50: 'Salem', 51: 'Dehradun', 52: 'Pantnagar', 53: 'Pithoragarh', 54: 'Dibrugarh', 55: 'Guwahati', 56: 'Jorhat', 57: 'Silchar', 58: 'Tezpur', 59: 'Lilabari', 60: 'Dimapur', 61: 'Gaya', 62: 'Patna', 63: 'Goa', 64: 'Hyderabad', 65: 'Imph

In [ ]:
## Replacing the Names with Indices using Dictionary
flightData.replace(cityDict, inplace=True)
print(flightData.to_string())

     Airport Names  Airport(Arrival)  Frequency per week
0                4                29                   7
1                4                 0                   7
2                4                55                  25
3                4                65                   7
4                4                 2                  77
5                5                43                  14
6                6                74                  13
7                6                27                  13
8                6                29                  76
9                6                30                   7
10               6                 7                   6
11               6                35                  14
12               6                40                   7
13               6                26                  27
14               6                 3                  55
15               6                43                  14
16               6             

In [ ]:
## Creating the Matrix with Zero Values
## len function is used to calculate the length of the dictionary
cityArray = np.zeros((len(cityDict), len(cityDict)))
print(cityArray)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
## Iterating the DataFrame to insert value at the adjacency matrix
for i in range(len(flightData)) :

    print(flightData.iloc[i, 0], flightData.iloc[i, 1], flightData.iloc[i, 2])
    cityArray[int(flightData.iloc[i, 0]), int(flightData.iloc[i, 1])] = int(flightData.iloc[i, 2])

4 29 7
4 0 7
4 55 25
4 65 7
4 2 77
5 43 14
6 74 13
6 27 13
6 29 76
6 30 7
6 7 6
6 35 14
6 40 7
6 26 27
6 3 55
6 43 14
6 51 13
6 0 172
6 95 6
6 63 27
6 55 6
6 31 7
6 64 59
6 37 40
6 39 6
6 67 39
6 68 12
6 81 7
6 69 13
6 12 13
6 20 6
6 70 6
6 2 29
6 21 29
6 108 6
6 1 88
6 76 13
6 79 13
6 62 6
6 8 7
6 77 41
6 73 7
6 71 6
6 22 20
7 6 6
7 13 6
8 6 7
8 1 7
9 1 7
10 0 14
10 1 21
11 1 7
12 6 12
12 1 7
13 29 14
13 7 6
13 3 14
13 0 42
13 63 21
13 64 14
13 67 10
13 68 7
13 2 28
13 1 7
13 76 7
13 71 7
14 29 15
14 0 49
14 64 7
14 1 22
14 76 14
15 55 14
15 65 4
15 2 21
16 67 4
17 35 7
17 29 7
17 0 28
17 2 21
17 1 7
17 84 21
18 29 7
18 0 14
18 64 7
18 2 7
18 1 7
19 31 3
19 53 7
20 6 6
20 0 7
20 1 14
21 6 36
21 29 41
21 3 7
21 51 6
21 0 147
21 63 8
21 64 20
21 2 28
21 1 63
21 62 14
21 77 7
21 73 7
22 6 19
22 6 13
22 29 27
22 40 7
22 3 18
22 51 3
22 0 127
22 61 15
22 64 36
22 67 11
22 38 12
22 2 33
22 1 56
23 0 7
24 29 7
24 51 2
24 0 87
24 64 7
24 67 7
24 2 7
24 1 16
24 62 11
24 73 14
25 0 3
26 6 23
26

In [ ]:
## tolist function converts the values to Float values. Hence specifying the type explicitly 
#print(np.matrix(cityArray.astype(np.int32).tolist()))
output_df = pd.DataFrame(cityArray)
output_df.rename(index=dict(inv_cityDict), columns=dict(inv_cityDict), inplace=True)

In [ ]:
## Adjacency matrix for a week (7 days)

output_df

Delhi  Mumbai  Kolkata  Chennai  ...  Patnagar  Kangra  Meerut  Bidar
Delhi        0.0   328.0    142.0     77.0  ...       4.0     6.0     0.0    0.0
Mumbai     457.0     0.0    178.0    154.0  ...       0.0     0.0     0.0    0.0
Kolkata    278.0   169.0      0.0    120.0  ...       0.0     0.0     0.0    0.0
Chennai    170.0   157.0    102.0      0.0  ...       0.0     0.0     0.0    0.0
Agartala     7.0     0.0     77.0      0.0  ...       0.0     0.0     0.0    0.0
...          ...     ...      ...      ...  ...       ...     ...     ...    ...
Pathankot    0.0     0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0
Patnagar     0.0     0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0
Kangra       0.0     0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0
Meerut       0.0     0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0
Bidar        0.0     0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0

[110 rows x 110 columns]

In [ ]:
p=output_df

In [ ]:
## Creating 110 adjacency matrix for entire duration ( 27th October 2019 to 28th March 2020)

n = 22  ## n=22 weeks or 152 days
output_df=np.multiply(p,n)

## Indegree adjacency matrix
output_df

Delhi  Mumbai  Kolkata  Chennai  ...  Patnagar  Kangra  Meerut  Bidar
Delhi          0.0  7216.0   3124.0   1694.0  ...      88.0   132.0     0.0    0.0
Mumbai     10054.0     0.0   3916.0   3388.0  ...       0.0     0.0     0.0    0.0
Kolkata     6116.0  3718.0      0.0   2640.0  ...       0.0     0.0     0.0    0.0
Chennai     3740.0  3454.0   2244.0      0.0  ...       0.0     0.0     0.0    0.0
Agartala     154.0     0.0   1694.0      0.0  ...       0.0     0.0     0.0    0.0
...            ...     ...      ...      ...  ...       ...     ...     ...    ...
Pathankot      0.0     0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0
Patnagar       0.0     0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0
Kangra         0.0     0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0
Meerut         0.0     0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0
Bidar          0.0     0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0

[110 rows x 110 columns]

In [ ]:
## Tranpose of data frame 
df=output_df.T

In [ ]:
## Outdegree adjacency matrix
df

Delhi   Mumbai  Kolkata  Chennai  ...  Patnagar  Kangra  Meerut  Bidar
Delhi         0.0  10054.0   6116.0   3740.0  ...       0.0     0.0     0.0    0.0
Mumbai     7216.0      0.0   3718.0   3454.0  ...       0.0     0.0     0.0    0.0
Kolkata    3124.0   3916.0      0.0   2244.0  ...       0.0     0.0     0.0    0.0
Chennai    1694.0   3388.0   2640.0      0.0  ...       0.0     0.0     0.0    0.0
Agartala      0.0      0.0   1716.0      0.0  ...       0.0     0.0     0.0    0.0
...           ...      ...      ...      ...  ...       ...     ...     ...    ...
Pathankot    66.0      0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0
Patnagar     88.0      0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0
Kangra      132.0      0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0
Meerut        0.0      0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0
Bidar         0.0      0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0

[110 rows x 110 columns]

In [ ]:
## Degree adjacency matrix
A=output_df+df

In [ ]:
## Degree adjacency matrix
A

Delhi   Mumbai  Kolkata  Chennai  ...  Patnagar  Kangra  Meerut  Bidar
Delhi          0.0  17270.0   9240.0   5434.0  ...      88.0   132.0     0.0    0.0
Mumbai     17270.0      0.0   7634.0   6842.0  ...       0.0     0.0     0.0    0.0
Kolkata     9240.0   7634.0      0.0   4884.0  ...       0.0     0.0     0.0    0.0
Chennai     5434.0   6842.0   4884.0      0.0  ...       0.0     0.0     0.0    0.0
Agartala     154.0      0.0   3410.0      0.0  ...       0.0     0.0     0.0    0.0
...            ...      ...      ...      ...  ...       ...     ...     ...    ...
Pathankot     66.0      0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0
Patnagar      88.0      0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0
Kangra       132.0      0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0
Meerut         0.0      0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0
Bidar          0.0      0.0      0.0      0.0  ...       0.0     0.0     0.0    0.0

[110 rows x 110 columns]

In [ ]:
## Normalizing the adjacency matrix by dividing with highest value

df=A.to_numpy()
dfmax, dfmin = df.max(), df.min()
df = (df - dfmin)/(dfmax - dfmin)
# Create the dataframe
A1=pd.DataFrame(df)
A1.rename(index=dict(inv_cityDict), columns=dict(inv_cityDict), inplace=True)

In [ ]:
## Normalized adjacency matrix by dividing with highest value

A1

Delhi    Mumbai   Kolkata  ...    Kangra  Meerut  Bidar
Delhi      0.000000  1.000000  0.535032  ...  0.007643     0.0    0.0
Mumbai     1.000000  0.000000  0.442038  ...  0.000000     0.0    0.0
Kolkata    0.535032  0.442038  0.000000  ...  0.000000     0.0    0.0
Chennai    0.314650  0.396178  0.282803  ...  0.000000     0.0    0.0
Agartala   0.008917  0.000000  0.197452  ...  0.000000     0.0    0.0
...             ...       ...       ...  ...       ...     ...    ...
Pathankot  0.003822  0.000000  0.000000  ...  0.000000     0.0    0.0
Patnagar   0.005096  0.000000  0.000000  ...  0.000000     0.0    0.0
Kangra     0.007643  0.000000  0.000000  ...  0.000000     0.0    0.0
Meerut     0.000000  0.000000  0.000000  ...  0.000000     0.0    0.0
Bidar      0.000000  0.000000  0.000000  ...  0.000000     0.0    0.0

[110 rows x 110 columns]

In [ ]:
## Normalizing the adjacency matrix by dividing each row elements with row summation
D=A.sum(axis=1)

In [ ]:
D

Delhi        147774.0
Mumbai       111496.0
Kolkata       75460.0
Chennai       66946.0
Agartala       5258.0
               ...   
Pathankot        66.0
Patnagar         88.0
Kangra          132.0
Meerut          132.0
Bidar           154.0
Length: 110, dtype: float64

In [ ]:
## Normalizing the adjacency matrix by dividing each row elements with row summation
A2=A.div(A.sum(axis=1), axis=0)
A2

Delhi    Mumbai   Kolkata  ...    Kangra  Meerut  Bidar
Delhi      0.000000  0.116868  0.062528  ...  0.000893     0.0    0.0
Mumbai     0.154893  0.000000  0.068469  ...  0.000000     0.0    0.0
Kolkata    0.122449  0.101166  0.000000  ...  0.000000     0.0    0.0
Chennai    0.081170  0.102202  0.072954  ...  0.000000     0.0    0.0
Agartala   0.029289  0.000000  0.648536  ...  0.000000     0.0    0.0
...             ...       ...       ...  ...       ...     ...    ...
Pathankot  1.000000  0.000000  0.000000  ...  0.000000     0.0    0.0
Patnagar   1.000000  0.000000  0.000000  ...  0.000000     0.0    0.0
Kangra     1.000000  0.000000  0.000000  ...  0.000000     0.0    0.0
Meerut     0.000000  0.000000  0.000000  ...  0.000000     0.0    0.0
Bidar      0.000000  0.000000  0.000000  ...  0.000000     0.0    0.0

[110 rows x 110 columns]

In [ ]:
## Normalizing the adjacency matrix by dividing with total matrix summation
S=A.sum().sum()

In [ ]:
S

1062952.0

In [ ]:
## Normalizing the adjacency matrix by dividing with total matrix summation
A3= A/S
A3

Delhi    Mumbai   Kolkata  ...    Kangra  Meerut  Bidar
Delhi      0.000000  0.016247  0.008693  ...  0.000124     0.0    0.0
Mumbai     0.016247  0.000000  0.007182  ...  0.000000     0.0    0.0
Kolkata    0.008693  0.007182  0.000000  ...  0.000000     0.0    0.0
Chennai    0.005112  0.006437  0.004595  ...  0.000000     0.0    0.0
Agartala   0.000145  0.000000  0.003208  ...  0.000000     0.0    0.0
...             ...       ...       ...  ...       ...     ...    ...
Pathankot  0.000062  0.000000  0.000000  ...  0.000000     0.0    0.0
Patnagar   0.000083  0.000000  0.000000  ...  0.000000     0.0    0.0
Kangra     0.000124  0.000000  0.000000  ...  0.000000     0.0    0.0
Meerut     0.000000  0.000000  0.000000  ...  0.000000     0.0    0.0
Bidar      0.000000  0.000000  0.000000  ...  0.000000     0.0    0.0

[110 rows x 110 columns]

In [ ]:
## Normalizing the adjacency matrix by dividing each column elements with column summation
A4=A2.T
A4

Delhi    Mumbai   Kolkata  ...  Kangra  Meerut  Bidar
Delhi      0.000000  0.154893  0.122449  ...     1.0     0.0    0.0
Mumbai     0.116868  0.000000  0.101166  ...     0.0     0.0    0.0
Kolkata    0.062528  0.068469  0.000000  ...     0.0     0.0    0.0
Chennai    0.036772  0.061365  0.064723  ...     0.0     0.0    0.0
Agartala   0.001042  0.000000  0.045190  ...     0.0     0.0    0.0
...             ...       ...       ...  ...     ...     ...    ...
Pathankot  0.000447  0.000000  0.000000  ...     0.0     0.0    0.0
Patnagar   0.000596  0.000000  0.000000  ...     0.0     0.0    0.0
Kangra     0.000893  0.000000  0.000000  ...     0.0     0.0    0.0
Meerut     0.000000  0.000000  0.000000  ...     0.0     0.0    0.0
Bidar      0.000000  0.000000  0.000000  ...     0.0     0.0    0.0

[110 rows x 110 columns]

In [ ]:
## Exporting the Normalized matrix A1

filepath = 'A1.xlsx'
A1.to_excel(filepath, index=True)

In [ ]:
## Exporting the Normalized matrix A2

filepath = 'A2.xlsx'
A2.to_excel(filepath, index=True)

In [ ]:
## Exporting the Normalized matrix A3

filepath = 'A3.xlsx'
A3.to_excel(filepath, index=True)

In [ ]:
## Exporting the Normalized matrix A4

filepath = 'A4.xlsx'
A4.to_excel(filepath, index=True)

In [ ]:
## Calculating D1
D1=A1
D1["sum"] = D1.sum(axis=1)

D1=D1["sum"]
D1

Delhi        8.556688
Mumbai       6.456051
Kolkata      4.369427
Chennai      3.876433
Agartala     0.304459
               ...   
Pathankot    0.003822
Patnagar     0.005096
Kangra       0.007643
Meerut       0.007643
Bidar        0.008917
Name: sum, Length: 110, dtype: float64

In [ ]:
## Calculating D2
D2=A2
D2["sum"] = D2.sum(axis=1)

D2=D2["sum"]
D2

Delhi        1.0
Mumbai       1.0
Kolkata      1.0
Chennai      1.0
Agartala     1.0
            ... 
Pathankot    1.0
Patnagar     1.0
Kangra       1.0
Meerut       1.0
Bidar        1.0
Name: sum, Length: 110, dtype: float64

In [ ]:
## Calculating D3
D3=A3
D3["sum"] = D3.sum(axis=1)

D3=D3["sum"]
D3

Delhi        0.139022
Mumbai       0.104893
Kolkata      0.070991
Chennai      0.062981
Agartala     0.004947
               ...   
Pathankot    0.000062
Patnagar     0.000083
Kangra       0.000124
Meerut       0.000124
Bidar        0.000145
Name: sum, Length: 110, dtype: float64

In [ ]:
## Calculating D3
D4=A4
D4["sum"] = D4.sum(axis=1)

D4=D4["sum"]
D4

Delhi        21.955184
Mumbai       12.734568
Kolkata      11.375370
Chennai       7.266534
Agartala      0.166282
               ...    
Pathankot     0.000447
Patnagar      0.000596
Kangra        0.000893
Meerut        0.003317
Bidar         0.001509
Name: sum, Length: 110, dtype: float64

In [ ]:
## Exporting D1

filepath = 'D1.xlsx'
D1.to_excel(filepath, index=True)

In [ ]:
## Exporting D2

filepath = 'D2.xlsx'
D2.to_excel(filepath, index=True)

In [ ]:
## Exporting D3

filepath = 'D3.xlsx'
D3.to_excel(filepath, index=True)

In [ ]:
## Exporting D4

filepath = 'D4.xlsx'
D4.to_excel(filepath, index=True)